### ISSUE TITLE
setAccessToken true generates error on local login.

### ISSUE THREAD

**Issue by sanandrea** [strongloop/loopback-component-passport#132]
In providers.json, if the option setAccessToken is true leads to an [error](https://gist.github.com/sanandrea/4da1c592a0ac714d5b0e5418ce3680c6).
This is due to the fact that after using loopback login the execution continues in passport-configurator.js. See my comment [here](https://github.com/strongloop/loopback-component-passport/commit/4cf8153a7b11ace76bf75977fa9ca238cf8910ad). I think it is a regression because in v 1.6.0 is correct

**Comment by jannyHou** [comment]
hey @sanandrea I am trying to reproduce your error, could you describe more about the steps to get this error:
I am using this example for debug https://github.com/strongloop/loopback-example-passport
Do I need to add `setAccessToken: true` in [local config](https://github.com/strongloop/loopback-example-passport/blob/master/providers.json.template#L2)? or [facebook config](https://github.com/strongloop/loopback-example-passport/blob/master/providers.json.template#L12)?
And can I get your error when I trigger local login or facebook login from browser?
Thanks a lot!

**Comment by sanandrea** [comment]
I set the setAccessToken true on local config and I triggered local login from browser.
Thank you!

**Comment by jannyHou** [comment]
I reproduced it on my local:
1. git clone https://github.com/strongloop/loopback-example-passport
2. add `setAccessToken: true` in local config
3. node .
4. signup a new account
5. logout then login with local account you created in step4

Error msg:
--- 

```
_http_outgoing.js:344
    throw new Error('Can\'t set headers after they are sent.');
    ^

Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)
    at ServerResponse.header (C:\Users\IBM_ADMIN\Desktop\loopback-projects\loopback-example-passport-empty\loopback-example-passport\node_modules\loopback\node_modules\express\lib\response.js:718:10)
    at ServerResponse.location (C:\Users\IBM_ADMIN\Desktop\loopback-projects\loopback-example-passport-empty\loopback-example-passport\node_modules\loopback\node_modules\express\lib\response.js:835:8)
    at ServerResponse.redirect (C:\Users\IBM_ADMIN\Desktop\loopback-projects\loopback-example-passport-empty\loopback-example-passport\node_modules\loopback\node_modules\express\lib\response.js:874:8)
    at allFailed (C:\Users\IBM_ADMIN\Desktop\loopback-projects\loopback-example-passport-empty\loopback-example-passport\node_modules\passport\lib\middleware\authenticate.js:125:20)
    at attempt (C:\Users\IBM_ADMIN\Desktop\loopback-projects\loopback-example-passport-empty\loopback-example-passport\node_modules\passport\lib\middleware\authenticate.js:160:28)
    at Strategy.strategy.fail (C:\Users\IBM_ADMIN\Desktop\loopback-projects\loopback-example-passport-empty\loopback-example-passport\node_modules\passport\lib\middleware\authenticate.js:277:9)
    at verified (C:\Users\IBM_ADMIN\Desktop\loopback-projects\loopback-example-passport-empty\loopback-example-passport\node_modules\passport-local\lib\strategy.js:82:30)
    at C:\Users\IBM_ADMIN\Desktop\loopback-projects\loopback-example-passport-empty\loopback-example-passport\node_modules\loopback-component-passport\lib\passport-configurator.js:317:17
    at C:\Users\IBM_ADMIN\Desktop\loopback-projects\loopback-example-passport-empty\loopback-example-passport\node_modules\loopback\common\models\user.js:312:9

```

**Comment by loay** [comment]
Hi @sanandrea 
Thanks for your pull request. Actually the issue is already reported https://github.com/strongloop/loopback-component-passport/issues/45
and I was working on it already. Unfortunately, your PR won't allow the emails to be verified if the `setAccessToken:true`
I will put more details into your PR.

**Comment by jannyHou** [comment]
@loay thank you for confirm. @sanandrea  Let's keep discussion in https://github.com/strongloop/loopback-component-passport/issues/45 , it's more detailed and more people involved. Thanks!
