### ISSUE TITLE
Local Passport Issue

### ISSUE THREAD

**Issue by benawarez** [strongloop/loopback-component-passport#171]
I'm able to successfully logon using google and facebook but when I logon using the Local Passport with  unverified email, I get the following:

Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)
    at ServerResponse.res.setHeader (F:\ScreenPostsWork\node_modules\loopback-explorer\node_modules\express\node_modules\connect\lib\patch.js:134:22)
    at ServerResponse.header (F:\ScreenPostsWork\node_modules\loopback\node_modules\express\lib\response.js:718:10)
    at ServerResponse.location (F:\ScreenPostsWork\node_modules\loopback\node_modules\express\lib\response.js:835:8)
    at ServerResponse.redirect (F:\ScreenPostsWork\node_modules\loopback\node_modules\express\lib\response.js:874:8)
    at complete (F:\ScreenPostsWork\node_modules\loopback-component-passport\node_modules\passport\lib\middleware\authenticate.js:248:26)
    at F:\ScreenPostsWork\node_modules\loopback-component-passport\node_modules\passport\lib\middleware\authenticate.js:257:15
    at pass (F:\ScreenPostsWork\node_modules\loopback-component-passport\node_modules\passport\lib\authenticator.js:421:14)
    at Authenticator.transformAuthInfo (F:\ScreenPostsWork\node_modules\loopback-component-passport\node_modules\passport\lib\authenticator.js:443:5)
    at F:\ScreenPostsWork\node_modules\loopback-component-passport\node_modules\passport\lib\middleware\authenticate.js:254:22
    at F:\ScreenPostsWork\node_modules\loopback-component-passport\node_modules\passport\lib\http\request.js:60:7
    at pass (F:\ScreenPostsWork\node_modules\loopback-component-passport\node_modules\passport\lib\authenticator.js:267:43)
    at serialized (F:\ScreenPostsWork\node_modules\loopback-component-passport\node_modules\passport\lib\authenticator.js:276:7)
    at F:\ScreenPostsWork\node_modules\loopback-component-passport\lib\passport-configurator.js:75:7
    at pass (F:\ScreenPostsWork\node_modules\loopback-component-passport\node_modules\passport\lib\authenticator.js:284:9)
    at Authenticator.serializeUser (F:\ScreenPostsWork\node_modules\loopback-component-passport\node_modules\passport\lib\authenticator.js:289:5)
    at IncomingMessage.req.login.req.logIn (F:\ScreenPostsWork\node_modules\loopback-component-passport\node_modules\passport\lib\http\request.js:50:29)
    at Strategy.strategy.success (F:\ScreenPostsWork\node_modules\loopback-component-passport\node_modules\passport\lib\middleware\authenticate.js:235:13)
    at verified (F:\ScreenPostsWork\node_modules\passport-local\lib\strategy.js:83:10)
    at F:\ScreenPostsWork\node_modules\loopback-component-passport\lib\passport-configurator.js:303:25
    at tokenHandler (F:\ScreenPostsWork\node_modules\loopback\common\models\user.js:228:9)
    at F:\ScreenPostsWork\node_modules\loopback-datasource-juggler\lib\relation-definition.js:1814:13

However, if I intentionally enter in the wrong password, I get the following error and my app crashes:
_http_outgoing.js:335
    throw new Error('Can\'t set headers after they are sent.');
          ^
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)
    at ServerResponse.res.setHeader (F:\ScreenPostsWork\node_modules\loopback-explorer\node_modules\express\node_modules\connect\lib\patch.js:134:22)
    at ServerResponse.header (F:\ScreenPostsWork\node_modules\loopback\node_modules\express\lib\response.js:718:10)
    at ServerResponse.location (F:\ScreenPostsWork\node_modules\loopback\node_modules\express\lib\response.js:835:8)
    at ServerResponse.redirect (F:\ScreenPostsWork\node_modules\loopback\node_modules\express\lib\response.js:874:8)
    at allFailed (F:\ScreenPostsWork\node_modules\loopback-component-passport\node_modules\passport\lib\middleware\authenticate.js:132:20)
    at attempt (F:\ScreenPostsWork\node_modules\loopback-component-passport\node_modules\passport\lib\middleware\authenticate.js:167:28)
    at Strategy.strategy.fail (F:\ScreenPostsWork\node_modules\loopback-component-passport\node_modules\passport\lib\middleware\authenticate.js:284:9)
    at verified (F:\ScreenPostsWork\node_modules\passport-local\lib\strategy.js:82:30)
    at F:\ScreenPostsWork\node_modules\loopback-component-passport\lib\passport-configurator.js:297:31
    at F:\ScreenPostsWork\node_modules\loopback\common\models\user.js:256:13
    at F:\ScreenPostsWork\node_modules\loopback\common\models\user.js:307:9
    at F:\ScreenPostsWork\node_modules\loopback\node_modules\bcryptjs\dist\bcrypt.js:261:17
    at F:\ScreenPostsWork\node_modules\loopback\node_modules\bcryptjs\dist\bcrypt.js:1198:21
    at Immediate.next (F:\ScreenPostsWork\node_modules\loopback\node_modules\bcryptjs\dist\bcrypt.js:1078:21)
    at Immediate._onImmediate (F:\ScreenPostsWork\node_modules\loopback\node_modules\continuation-local-storage\node_modules\async-listener\glue.js:188:31)
    at processImmediate [as _immediateCallback](timers.js:367:17)

Below is my local passport provider:

  "local": {
    "provider": "local",
    "module": "passport-local",
    "usernameField": "email",
    "passwordField": "password",
    "authPath": "/auth/local",
    "successRedirect": "/api/Customers/me",
    "failureRedirect": "/index.html#/Login",
    "failureFlash": true,
    "setAccessToken": true  
  }

Please advise.

Thanks.

**Comment by benawarez** [comment]
Update:
When I remove "setAccessToken": true option, I get a response of status 200 when I'm supposed to be expecting the "Invalid username/password or email has not been verified" error message as  defined in the passport-configurator.js.

Any thoughts?
