### ISSUE TITLE
Middleware error

### ISSUE THREAD

**Issue by ciulhycutza** [strongloop/loopback-component-passport#64]
Hi.
I'm very new to loopback. I tried to implement passport.js but I'm getting this error.

```
Error: passport.initialize() middleware not in use
    at IncomingMessage.req.login.req.logIn (/Users/gabrielciulei/loop/node_modules/passport-google-oauth/node_modules/passport-oauth/node_modules/passport/lib/passport/http/request.js:30:30)
    at /Users/gabrielciulei/loop/common/models/user-identity.js:22:17
    at /Users/gabrielciulei/loop/node_modules/loopback-datasource-juggler/lib/dao.js:1408:5
    at allCb (/Users/gabrielciulei/loop/node_modules/loopback-datasource-juggler/lib/dao.js:1339:7)
    at /Users/gabrielciulei/loop/node_modules/loopback-connector-couchbase/lib/cb.js:386:4
    at /Users/gabrielciulei/loop/node_modules/loopback-connector-couchbase/lib/cb.js:117:5
    at Request._callback (/Users/gabrielciulei/loop/node_modules/loopback-connector-couchbase/node_modules/couchbase/lib/bucket.js:353:14)
    at Request.self.callback (/Users/gabrielciulei/loop/node_modules/loopback-connector-couchbase/node_modules/couchbase/node_modules/request/request.js:199:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/Users/gabrielciulei/loop/node_modules/loopback-connector-couchbase/node_modules/couchbase/node_modules/request/request.js:1160:14)
```

server.js
```
var loopback = require('loopback');
var boot = require('loopback-boot');
var path = require('path');

var app = module.exports = loopback();

// Passport configurators..
var loopbackPassport = require('loopback-component-passport');
var PassportConfigurator = loopbackPassport.PassportConfigurator;
var passportConfigurator = new PassportConfigurator(app);

// Bootstrap the application, configure models, datasources and middleware.
// Sub-apps like REST API are mounted via boot scripts.
boot(app, __dirname);

/*
 * body-parser is a piece of express middleware that
 *   reads a form's input and stores it as a javascript
 *   object accessible through `req.body`
 *
 */
var bodyParser = require('body-parser');

/**
 * Flash messages for passport
 *
 * Setting the failureFlash option to true instructs Passport to flash an
 * error message using the message given by the strategy's verify callback,
 * if any. This is often the best approach, because the verify callback
 * can make the most accurate determination of why authentication failed.
 */
var flash = require('express-flash');

// attempt to build the providers/passport config
var config = {};
try {
	config = require('../providers.json');
} catch (err) {
	console.trace(err);
	process.exit(1); // fatal
}

// Set up the /favicon.ico
app.use(loopback.favicon());

// request pre-processing middleware
app.use(loopback.compress());



app.set('view engine', 'ejs'); // LoopBack comes with EJS out-of-box
app.set('views', path.resolve(__dirname, 'views'));
app.use(loopback.static(path.resolve(__dirname, '../client')));

// to support JSON-encoded bodies
app.use(bodyParser.json());
// to support URL-encoded bodies
app.use(bodyParser.urlencoded({
	extended: true
}));

// The access token is only available after boot
app.use(loopback.token({
  model: app.models.accessToken
}));

app.use(loopback.cookieParser(app.get('cookieSecret')));
app.use(loopback.session({
	secret: 'kitty',
	saveUninitialized: true,
	resave: true
}));
passportConfigurator.init();

// We need flash messages to see passport errors
app.use(flash());

passportConfigurator.setupModels({
	userModel: app.models.user,
	userIdentityModel: app.models.userIdentity,
	userCredentialModel: app.models.userCredential
});
for (var s in config) {
	var c = config[s];
	c.session = c.session !== false;
	passportConfigurator.configureProvider(s, c);
}
var ensureLoggedIn = require('connect-ensure-login').ensureLoggedIn;

// Requests that get this far won't be handled
// by any middleware. Convert them into a 404 error
// that will be handled later down the chain.
app.use(loopback.urlNotFound());

// The ultimate error handler.
app.use(loopback.errorHandler());

app.start = function() {
  // start the web server
  return app.listen(function() {
    app.emit('started');
    console.log('Web server listening at: %s', app.get('url'));
  });
};

// start the server if `$ node server.js`
if (require.main === module) {
  app.start();
}
```

routes.js
```
module.exports = function(app) {
  var router = app.loopback.Router();

  router.get('/tasks', function(req, res) {
    console.log("USER", req.user);

    res.render('layout', {
      projectData: 'var currentProject = null;',
      viewPath: './tasks'
    });
  });
  app.use(router);
};
```

middleware.json
```
{
  "initial:before": {
    "loopback#favicon": {}
  },
  "initial": {
    "compression": {}
  },
  "session": {
  },
  "auth": {
  },
  "parse": {
  },
  "routes": {
    "loopback#status": {
      "paths": "/"
    }
  },
  "files": {
  },
  "final": {
    "loopback#urlNotFound": {}
  },
  "final:after": {
    "errorhandler": {}
  }
}
```

Can anybody tell me what's wrong?

Thank you.

**Comment by raymondfeng** [comment]
You probably call the following line too late:

passportConfigurator.init();

**Comment by ciulhycutza** [comment]
It works. I had to call it before boot function. 
Thank you very much.

**Comment by gausie** [comment]
I also have this problem. However, I need to call it after the boot function so that the config is loaded into `app` (so I can do things like `app.get('sessionSecret')`)

**Comment by gianko** [comment]
I have a problem when using:

<pre>
app.middleware('auth', loopback.token({
  model: app.models.AccessToken
}));
</pre>

Then context.active gets empty in: 
<pre>
var context = loopback.getCurrentContext();
</pre>

**Comment by superkhau** [comment]
@gausie Doing it after boot makes sense if you want to make sure the default LB ocnfigs are loaded first.
@gausie Please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.

Closing as this is resolved by @raymondfeng.

**Comment by mike-aungsan** [comment]
@raymondfeng 
I have the same problem no matter where I put this line before or after boot.
passportConfigurator.init()

So finally I did like this
app.middleware('session:before', loopback.cookieParser(crypto.randomBytes(64).toString('base64')))

Interesting thing is that example code work fine. But I use all the latest version in my package.json  which probably make it not work.

And I know it is not a good place to ask but since I got no response anywhere, 

Why is this component not pure REST API?
I want to see token response from this login API.
http://localhost/auth/local


{
  "dependencies": {

    "compression": "^1.0.3",
    "cors": "^2.5.2",
    "loopback": "^2.22.0",
    "loopback-boot": "^2.6.5",
    "loopback-component-explorer": "^2.1.0",
    "loopback-datasource-juggler": "^2.39.0",
    "serve-favicon": "^2.0.1",
    
    "ldapjs": "mcavage/node-ldapjs#acc1ca8f4314fd9d67561feabc8ce4c235076a5e",
    "ldapauth-fork": "latest",
    
    "mongodb": "latest",
    
    "body-parser": "latest",
    "express-flash": "latest",
    "express-session": "latest",
    "cookie-parser": "latest",
    "connect-ensure-login": "latest",
    
    "passport": "latest",
    "passport-ldapauth": "latest",
    
    "loopback-connector-mongodb": "latest",
    "loopback-component-passport": "latest",
    "loopback-component-storage": "latest"
    
  }
}
